### ISSUE TITLE
Fix to forbiden alpine libs

### ISSUE THREAD

**Issue by mendexjs** [devfelipereis/laravel-docker-nginx#1]
ADD https://packages.whatwedo.ch/php-alpine.rsa.pub /etc/apk/keys/php-alpine.rsa.pub
RUN echo "https://packages.whatwedo.ch/php-alpine/v3.11/php-7.4" >> /etc/apk/repositories

I'm having the same build problem caused by forbidden alpine libs. To fix this, I am using these urls. Try if that can help you too.

**Comment by devfelipereis** [comment]
I'm waiting for an oficial fix. More info in https://github.com/codecasts/php-alpine/issues/131

Thanks!
